impl replace and search functions
Cr1sPet/ru-study-ruby pull request #1
Opened 2022-10-07 08:27 UTC by CrsPet

2022-10-07 15:28 UTC, greybutton requested changes

2022-10-07 15:28 UTC, greybutton commented on test/exercise/arrays/solution.rb
> +        (1...array.length).each do |i|
почему сразу на массиве each не использовать?

2022-10-07 16:17 UTC, CrsPet commented on test/exercise/arrays/solution.rb
> +        (1...array.length).each do |i|
Рассматривал этот вариант, но хотел пропустить в цикле обход array[0], т.к. относительно него сравниваю все остальные элементы, поэтому выбрал данный вариант. Использование each было бы более читебелно, думаю

2022-10-07 16:22 UTC, greybutton commented on test/exercise/arrays/solution.rb
> +        (1...array.length).each do |i|
читаемость лучше выбирать, пусть машина страдает, а не человек)

2022-10-07 16:26 UTC, CrsPet commented on test/exercise/arrays/solution.rb
> +        (1...array.length).each do |i|
хорошо, передалю, спасибо)

2022-10-08 09:13 UTC, greybutton approved these changes

2022-10-08 10:47 UTC, merged